
name: tests

on: [push]

jobs:
  unit-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run all unit tests
      run: |
        echo Run test
        npm install
        npm run test
            
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check for linting
      run: |
        echo Run lint
        npm install
        npm run lint

  superlint:
    
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest
    
        ##################
        # Load all steps #
        ##################
        steps:
          ##########################
          # Checkout the code base #
          ##########################
          - name: Checkout Code
            uses: actions/checkout@v2
    
          ################################
          # Run Linter against code base #
          ################################
          - name: Lint Code Base
            uses: github/super-linter@v3
            env:
              VALIDATE_ALL_CODEBASE: false
              DEFAULT_BRANCH: master
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
